engines:
  one:
    # Engine name is in MiniMessage format.
    # https://docs.advntr.dev/minimessage/format.html
    name: "<red>Engine Level 1</red>"
    
    # Multiplier of the velocity when holding the item.
    multiplier: 0.5
    
    # Material of the resulting item.
    material: "smoker"
    
    ingredients:
      B: "coal_block"
      C: "copper_ingot"
      I: "iron_ingot"
      R: "redstone"
      P: "piston"
    
    # Recipe that is registered (requires a restart!)
    recipe:
      - "IRI"
      - "CPC"
      - "CBC"

  two:
    name: "<red>Engine Level 2</red>"
    multiplier: 1.0
    material: "furnace"
    
    ingredients:
      D: "diamond"
      # You can use speedyboats:key to reference another engine.
      S: "speedyboats:one"
      G: "gold_ingot"
      P: "piston"
    
    recipe:
      - "DDD"
      - "GSG"
      - "GPG"

  three:
    name: "<red>Engine Level 3</red>"
    multiplier: 2.0
    material: "blast_furnace"
    
    ingredients:
      N: "netherite_ingot"
      S: "nautilus_shell"
      B: "speedyboats:two"
      P: "piston"
    
    recipe:
      - " S "
      - "NBN"
      - "NPN"
