main: de.sivery.speedyboats.SpeedyBoats
name: SpeedyBoats
version: '1.1.1'
api-version: '1.20'
description: Give your boats a little extra SPEEED
author: Sivery
website: github.com/flerouwu/speedyboats
commands:
  boats:
    description: Opens boat engine recipes and admin give command.
    usage: /boats | /boats give <engine>
    permission: speedyboats.use
permissions:
  speedyboats.use:
    description: Allows using /boats recipe viewer
    default: true
  speedyboats.admin:
    description: Allows giving engine items via /boats give <engine>
    default: op
